#!/usr/bin/env php

/*******************************************************************************

Author: Heini Holm Andersen
Version: 2.1.1
Build: 1011
First release created on: 20 March 2015
Latest build created on: 17 August 2017
Purpose: For sending out responsive and easy to read email alert notifications.

--------------------------------------------------------------------------------

Requirements:

 1. Copy the php-html-email folder to the Nagios plugins directory and make sure all files are owned by the nagios user and also that they are executable!
 2. For the host and services notification alerts, please add these lines to your Nagios commands list:

    # 'notify-host-by-email-html' command definition
      define command {
        	command_name	notify-host-by-email-html
      command_line    $USER1$/php-html-email/nagios_host_mail "$NOTIFICATIONTYPE$" "$HOSTNAME$" "$HOSTALIAS$" "$HOSTSTATE$" "$HOSTADDRESS$" "$HOSTOUTPUT$" "$SHORTDATETIME$" "$CONTACTEMAIL$" "$TOTALHOSTSUP$" "$TOTALHOSTSDOWN$" "$NOTIFICATIONAUTHOR$" "$NOTIFICATIONCOMMENT$" "$LONGDATETIME$" "$HOSTDURATION$" "$HOSTDURATIONSEC$" "$LASTHOSTCHECK$" "$LASTHOSTSTATECHANGE$" "$NOTIFICATIONISESCALATED$" "$HOSTATTEMPT$" "$MAXHOSTATTEMPTS$" "$NOTIFICATIONRECIPIENTS$"
      }

    # 'notify-service-by-email-html' command definition
      define command {
          command_name	notify-service-by-email-html
      command_line	$USER1$/php-html-email/nagios_service_mail "$NOTIFICATIONTYPE$" "$HOSTNAME$" "$HOSTALIAS$" "$HOSTSTATE$" "$HOSTADDRESS$" "$SERVICEOUTPUT$" "$SHORTDATETIME$" "$SERVICEDESC$" "$SERVICESTATE$" "$CONTACTEMAIL$" "$SERVICEDURATIONSEC$" "$SERVICEEXECUTIONTIME$" "$TOTALSERVICESWARNING$" "$TOTALSERVICESCRITICAL$" "$TOTALSERVICESUNKNOWN$" "$LASTSERVICEOK$" "$LASTSERVICEWARNING$" "$SERVICENOTIFICATIONNUMBER$" "$LONGSERVICEOUTPUT$" "$NOTIFICATIONAUTHOR$" "$NOTIFICATIONCOMMENT$" "$SERVICEDURATION$" "$NOTIFICATIONISESCALATED$" "$SERVICEATTEMPT$" "$MAXSERVICEATTEMPTS$" "$NOTIFICATIONRECIPIENTS$"
      }

 3. Add the command names to your contact notifications settings, like seen below:
    service_notification_commands	notify-service-by-email-html
    host_notification_commands	notify-host-by-email-html

*******************************************************************************/

<?php

require_once dirname(__FILE__) . '/PHPMailer/PHPMailerAutoload.php';

/* Arguments containing Nagios Alert/Notification Info */
array_shift($argv);
$f_notify_type =array_shift($argv);  /*1*/
$f_host_name =array_shift($argv);  /*2*/
$f_host_alias =array_shift($argv);  /*3*/
$f_host_state =array_shift($argv);  /*4*/
$f_host_address =array_shift($argv);  /*5*/
$f_host_output =array_shift($argv);  /*6*/
$f_long_date =array_shift($argv);  /*7*/
$f_to  =array_shift($argv);  /*8*/
$f_totalup  =array_shift($argv);  /*9*/
$f_totaldown=array_shift($argv);  /*10*/
$f_ackauthor= array_shift($argv);  /*11*/
$f_ackcomment= array_shift($argv);  /*12*/
$f_long_datetime= array_shift($argv);  /*13*/
$f_host_duration= array_shift($argv);  /*14*/
$f_host_duration_sec= array_shift($argv);  /*15*/
$f_host_last_state_check= array_shift($argv);  /*16*/
$f_host_last_state_change= array_shift($argv);  /*17*/
$f_notification_escalation_state= array_shift($argv);  /*18*/
$f_host_attempt_state= array_shift($argv);  /*19*/
$f_max_host_attempt_state= array_shift($argv);  /*20*/
$f_all_recipients= array_shift($argv);  /*21*/

$f_date_year = date("Y");

/* Defaults */
$f_color="#5D6D7E";
$f_ackauthor_desc="Acknowledged Author:";
$f_ackcomment_desc="Acknowledged Comment:";

/* Build type of alert */
if($f_notify_type=="PROBLEM") {
  $f_color="#FF0000";
  $f_ackauthor_desc="Acknowledged Author:";
  $f_ackcomment_desc="Acknowledged Comment:";
}
if($f_notify_type=="RECOVERY") {
  $f_color="#00FF00";
  $f_ackauthor_desc="Acknowledged Author:";
  $f_ackcomment_desc="Acknowledged Comment:";
}
if($f_notify_type=="ACKNOWLEDGEMENT") {
  $f_color="#AEB6BF";
  $f_ackauthor_desc="Acknowledged Author:";
  $f_ackcomment_desc="Acknowledged Comment:";
}
if($f_notify_type=="FLAPPINGSTART") {
  $f_color="#800000";
  $f_ackauthor_desc="Flapping Author:";
  $f_ackcomment_desc="Flapping Comment:";
}
if($f_notify_type=="FLAPPINGSTOP") {
  $f_color="#008000";
  $f_ackauthor_desc="Flapping Author:";
  $f_ackcomment_desc="Flapping Comment:";
}
if($f_notify_type=="FLAPPINGDISABLED") {
  $f_color="#F7FE2E";
  $f_ackauthor_desc="Flapping Author:";
  $f_ackcomment_desc="Flapping Comment:";
}
if($f_notify_type=="DOWNTIMESTART") {
  $f_color="#5DADE2";
  $f_ackauthor_desc="Scheduled Downtime by:";
  $f_ackcomment_desc="Comment for Scheduled Downtime:";
}
if($f_notify_type=="DOWNTIMEEND") {
  $f_color="#48C9B0";
  $f_ackauthor_desc="Scheduled Downtime by:";
  $f_ackcomment_desc="Comment for Scheduled Downtime:";
}
if($f_notify_type=="DOWNTIMECANCELLED") {
  $f_color="#AF7AC5";
  $f_ackauthor_desc="Scheduled Downtime by:";
  $f_ackcomment_desc="Comment for Scheduled Downtime:";
}
if($f_notify_type=="CUSTOM") {
  $f_color="#5D6D7E";
  $f_ackauthor_desc="Custom Author:";
  $f_ackcomment_desc="Custom Comment:";
}

/* Check if acknowledgement is present and if so, then add HTML code */
if($f_ackauthor!="" && $f_ackcomment!=""){
  $f_ackauthor_status = '
    <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">' . $f_ackauthor_desc . '</h4>
    <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_ackauthor . '</h2>
  ';

  $f_ackcomment_status = '
    <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">' . $f_ackcomment_desc . '</h4>
    <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_ackcomment . '</h2>
  ';

  $f_ackauthor_status_none_html = $f_ackauthor_desc;
  $f_ackauthor_status_none_html .= ' ';
  $f_ackauthor_status_none_html .=  $f_ackauthor;

  $f_ackcomment_status_none_html = $f_ackcomment_desc;
  $f_ackcomment_status_none_html .= ' ';
  $f_ackcomment_status_none_html .= $f_ackcomment;
}

/* Check if acknowledgement is present and if so, then add HTML code */
if($f_notification_escalation_state==0){
  $f_notification_escalation_state_status = '
    <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Incident Escalated:</h4>
    <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">No</h2>
  ';

  $f_notification_escalation_state_status_none_html = 'Incident Escalated: No';
}

if($f_notification_escalation_state==1){
  $f_notification_escalation_state_status = '
    <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Incident Escalated:</h4>
    <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">Yes</h2>
  ';

  $f_notification_escalation_state_status_none_html = 'Incident Escalated: Yes';
}

/* Build the Nagios alert/notification, email body/content */
/* NONE HTML EMAIL CONTENT */
$message = '
***** Nagios *****

Notification Type: ' .$f_notify_type. '
Hostname: ' .$f_host_name. '
Hostalias: ' .$f_host_alias. '
State: ' .$f_host_state. '
Address: ' .$f_host_address. '
Date/Time: ' .$f_long_datetime. '
' .$f_notification_escalation_state_status_none_html. '
' .$f_ackauthor_status_none_html. '
' .$f_ackcomment_status_none_html. '

Info:
' .$f_host_output. '

';

/* HTML EMAIL CONTENT */
$HTMLmessage = '

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Nagios Email Notification Alert">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="x-apple-disable-message-reformatting">
    <title>' . $f_host_alias . '</title>

    <!--[if mso]>
        <style>
            * {
                font-family: sans-serif !important;
            }
        </style>
    <![endif]-->

    <!--[if !mso]><!-->
        <link href="https://font.internet.fo:8443/stylesheet.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <!--<![endif]-->

    <style>

        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }

        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        div[style*="margin: 16px 0"] {
            margin:0 !important;
        }

        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }
        table table table {
            table-layout: auto;
        }

        img {
            -ms-interpolation-mode:bicubic;
        }

        *[x-apple-data-detectors],	/* iOS */
        .x-gmail-data-detectors, 	/* Gmail */
        .x-gmail-data-detectors *,
        .aBn {
            border-bottom: 0 !important;
            cursor: default !important;
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        .a6S {
	        display: none !important;
	        opacity: 0.01 !important;
        }
        img.g-img + div {
	        display:none !important;
	   	}

        .button-link {
            text-decoration: none !important;
        }

        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) { /* iPhone 6 and 6+ */
            .email-container {
                min-width: 375px !important;
            }
        }

    </style>

    <style>

        .button-td,
        .button-a {
            transition: all 100ms ease-in;
        }
        .button-td:hover,
        .button-a:hover {
            background: #555555 !important;
            border-color: #555555 !important;
        }

        @media screen and (max-width: 600px) {

			.email-container p {
				font-size: 17px !important;
				line-height: 22px !important;
			}

		}

	</style>

	<!--[if gte mso 9]>
	<xml>
		<o:OfficeDocumentSettings>
			<o:AllowPNG/>
			<o:PixelsPerInch>96</o:PixelsPerInch>
		</o:OfficeDocumentSettings>
	</xml>
	<![endif]-->

</head>
<body width="100%" bgcolor="#f6f6f6" style="margin: 0;line-height:1.4;padding:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;">
	<center style="width: 100%; background: #f6f6f6; text-align: left;">

		<div style="display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;">
			[' .$f_notify_type. '] Host: ' .$f_host_alias. ' (' .$f_host_name. ') is ' .$f_host_state. '. ***************************************************************************************************************************************
		</div>

		<div style="max-width: 600px; padding: 10px 0; margin: auto;" class="email-container">
			<!--[if mso]>
			<table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" align="center">
			<tr>
			<td>
			<![endif]-->

			<table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="95%" style="max-width: 600px;">
				<tr>
					<td bgcolor="#ffffff" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;-webkit-border-top-right-radius: 25px;-webkit-border-top-left-radius: 25px;-moz-border-top-right-radius: 25px;-moz-border-top-left-radius: 25px;border-top-right-radius: 25px;border-top-left-radius: 25px;-webkit-border-bottom-right-radius: 25px;-webkit-border-bottom-left-radius: 25px;-moz-border-bottom-right-radius: 25px;-moz-border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;border-bottom-left-radius: 25px;">
            <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" align="center" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;-webkit-border-top-right-radius: 25px;-webkit-border-top-left-radius: 25px;-moz-border-top-right-radius: 25px;-moz-border-top-left-radius: 25px;border-top-right-radius: 25px;border-top-left-radius: 25px;">
                <tbody>
                  <tr>
                    <td style="background-color:#424242;-webkit-border-top-right-radius: 25px;-webkit-border-top-left-radius: 25px;-moz-border-top-right-radius: 25px;-moz-border-top-left-radius: 25px;border-top-right-radius: 25px;border-top-left-radius: 25px;">
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#ffffff; text-align:center;">Alert Notification</h2>
                    </td>
                  </tr>
                  <tr>
                    <td style="background-color:' .$f_color. ';">
                      <h1 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; padding:0; margin:10px; color:#ffffff; text-align:center;">' .$f_notify_type. '</h1>
                    </td>
                  </tr>
                </tbody>
            </table>
            <table border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;border-left-style: solid;border-right-style: solid;border-color: #d3d3d3;border-width: 1px;">
              <td style="font-size:16px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      <h5 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#b0b0b0; text-align:right; padding-right:5%;">' . $f_host_attempt_state . '/' . $f_max_host_attempt_state . '</h5>
                      <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; text-align:center; text-decoration:underline;">Host:</h4>
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:26px; text-align:center;">' . $f_host_name . '</h2>
                      <h5 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#b0b0b0; text-align:center;">is</h5>
                      <h1 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:30px; color:' .$f_color. ';text-align:center;">' . $f_host_state . '</h1>
                      <h5 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#b0b0b0; text-align:center;">for: ' . $f_host_duration . '</h5>
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%; text-decoration:underline;">Hostalias:</h4>
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_host_alias . '</h2>
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Host Address:</h4>
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_host_address . '</h2>
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Last Check:</h4>
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_long_date . '</h2>
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Status Information:</h4>
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_host_output . '</h2>
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      <h4 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:15px; color:#b0b0b0; padding-left:3%;text-decoration:underline;">Notified Recipients:</h4>
                      <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; font-size:20px; padding-left:5%;">' . $f_all_recipients . '</h2>
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      ' . $f_notification_escalation_state_status . '
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      ' . $f_ackauthor_status . '
                    </td>
                  </tr>
                </tbody>
                <td style="font-size:9px;vertical-align:top;">&nbsp;</td>
                <tbody>
                  <tr>
                    <td width="98%" style="vertical-align:middle;font-size:14px;width:98%;margin:0 10px 0 10px;">
                      ' . $f_ackcomment_status . '
                    </td>
                  </tr>
                </tbody>
              <td style="font-size:16px;vertical-align:top;">&nbsp;</td>
            </table>
            <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate;mso-table-lspace:0pt;mso-table-rspace:0pt;width:100%;-webkit-border-bottom-right-radius: 25px;-webkit-border-bottom-left-radius: 25px;-moz-border-bottom-right-radius: 25px;-moz-border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;border-bottom-left-radius: 25px;">
              <tbody>
                <tr>
                  <td style="background-color:' .$f_color. ';">
                    <h1 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; padding:0; margin:10px; color:#ffffff; text-align:center;">' .$f_notify_type. '</h1>
                  </td>
                </tr>
                <tr>
                  <td style="background-color:#424242;-webkit-border-bottom-right-radius: 25px;-webkit-border-bottom-left-radius: 25px;-moz-border-bottom-right-radius: 25px;-moz-border-bottom-left-radius: 25px;border-bottom-right-radius: 25px;border-bottom-left-radius: 25px;">
                    <h2 style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; margin:0; color:#ffffff; text-align:center;">Alert Notification</h2>
                  </td>
                </tr>
              </tbody>
            </table>
					</td>
				</tr>
			</table>
      <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;">
        <tr>
          <td style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; vertical-align:middle; color: #999999; text-align: center; padding: 40px 10px;width: 100%;" class="x-gmail-data-detectors">
            <span style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; color:#999999; text-align:center;">
              Copyright &#169; 2014-' .$f_date_year. ' &#124; <a href="mailto:hhan@mail.fo?subject=Nagios-HTML-Email-Notifications" style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; text-decoration:underline; color:#000000;">Heini Holm Andersen</a>
            </span>
            <br>
            <span style="font-family: CoconPro-BoldCond, Open Sans, Verdana, sans-serif; color:#999999; text-align:center;">
              All Rights Reserved.
            </span>
            <br>
            <br>
          </td>
        </tr>
      </table>
			<!--[if mso]>
			</td>
			</tr>
			</table>
			<![endif]-->
		</div>

    </center>
</body>
</html>
';

$mail = new PHPMailer;
//$mail->SMTPDebug = 3; // Enable verbose debug output
$mail->isSMTP(); // Set mailer to use SMTP
$mail->Host = 'localhost';	// Specify main and backup SMTP servers
$mail->SMTPAuth = false; // Enable SMTP authentication

$mail->From = 'nagios@localhost.com';
$mail->FromName = 'Nagios';
$mail->addAddress($f_to); // Add a recipient + Name is optional "$mail->addAddress('joe@example.net', 'Joe User');"
$mail->isHTML(true); // Set email format to HTML
$mail->WordWrap = 50; // Set word wrap to 50 characters

$mail->Subject = '*** '.$f_notify_type.': '.$f_host_name.' is '.$f_host_state.' ***';
$mail->AltBody = $message;
$mail->Body = $HTMLmessage;

if(!$mail->send()) {
	echo 'Message could not be sent.<br>';
	echo 'Mailer Error: ' . $mail->ErrorInfo . '<br>';
} else {
	echo 'Message has been sent<br>';
}

?>
